### PR TITLE
Change message based on result of importing contacts.

### PR DESCRIPTION
**Pull request by happyman125**
Fixes #support#33

### Changes description

  - change message for details of importing contacts

### CODE REVIEW

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Is there any reason you are duplicating the error message and not raising an exception for the error catch?
Also, there is a new `any` type and other details you may want to consider: https://deepsource.io/gh/CTemplar/webclient/run/fcf6552c-c193-4c4d-83a2-c4337da3ddc2/javascript/

**Comment by The-Hidden-Hand** [comment]
Sometimes they offer an "auto-fix" option:

image

**Comment by happyman125** [comment]
@The-Hidden-Hand there can be error case, not involved in error catch so I think Nitish added detail status.
Also, about deepsource, I can't see autofix on my side. what should I do to see autofix?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Ok, I was saying only to have one error when no contacts were imported. In Python, I would raise the exception and reuse the message; you may have other reasons.

About DeepSource, this is how it looks for me:
image

Some have an auto fix. I think it asked me to accept and enable permissions on Github.

**Pull request merged**
