### PR TITLE
delete safe sanitize on external link

### LINKED ISSUE #976: Enforce 'noreferrer noopener' in all external links
### Description

Links to cross-origin destinations are unsafe, (for example in index.html). Don't use target="_blank" without rel="noreferrer noopener". In older browsers, the page being linked to will be able to access the window object (using the window.opener property), giving access to data associated, and it may also allow the other page to redirect your page to a malicious URL.

### PR DESCRIPTION
**Pull request by happyman125**
Fixes #976

### Changes description

  - delete safe sanitize on external link

### CODE REVIEW

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Is this disabling any function or will create any side effect other than solving the issue?

**Comment by happyman125** [comment]
@The-Hidden-Hand this code removed rel attributes from a tag. I am not sure side effects and which one is better solution.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Then I cannot merge it until we are certain. We can't disable email sanitization. In any case, we whitelist `rel='noopener noreferrer'` but do not disable anything else, or it may open the door to XSS vulnerabilities.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Give some feedback on what to do.

**Comment by happyman125** [comment]
@The-Hidden-Hand I am not sure how we can use both of them

**Comment by superdev0714** [comment]
We should not remove sanitize.
I think we should update sanitize module for this task and #948 .

Updating for sanitize module should be as following...
1. Keeping `rel='noopener noreferrer'` attribute, if the link tag has.
2. Adding `rel='noopener noreferrer'`, if it doesn't have
3. Adding the javascript call to raise the modal to ask whether continue or not, if needed

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Any update?

**Comment by happyman125** [comment]
@The-Hidden-Hand We implemented new feature as you know, I mean confirm message when go to external link.
In this case, we add rel attribute after confirmed so I think we don't need to delete sanitize.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Ok, I close it.

**Pull request closed without merging**
