### PR TITLE
Add additional loading bar

### LINKED ISSUE #1077: The loading animation should wait until the website is truly ready
### Actual behavior

When I load the website for the first time or after a page refresh, I can see my membership is free, the dark mode isn't active, my custom CSS is not applied, and other details, for a while until my parameters are applied.

### Expected behavior

The loading animation should wait until the website is truly ready for display.

### PR DESCRIPTION
**Pull request by happyman125**
Fixes #1077 

### Changes description

  - add loading bar till data is loaded

### CODE REVIEW

**Comment by happyman125** [comment]
I found errors on past implementation so now I implemented new approach.

**Review by The-Hidden-Hand — CHANGES_REQUESTED** [review]
@happyman125 
There is one loading function already. I believe the right solution is to make it work as expected.
Could you elaborate on why you've taken this approach?

**Comment by happyman125** [comment]
@The-Hidden-Hand I checked carefully and implemented one solution before. I also know there is one loading on app component. but To implement this task exactly, We should detect all of user settings are loaded or not.
And then we can disable loading. But we can detect this on mail sidebar component and loading bar exists on app component. So if we use app loading bar, we should send any status to app component.

Also, there is two cases for this task. First one is when login and second one is when load page.
In these two cases, there are other conflicts to handle loading if we use origin loading bar.
As you know, I already implemented like that but after testing of cases, I found several issues of this implementation, Especially, on login page.

So I thought and decided to use additional loading bar to display loading status of user settings like I implemented.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Ok, thanks for explaining.

**Pull request merged**
