### PR TITLE
Git 957

### LINKED ISSUE #957: Older browsers like IE doesn't display the expected 'unsupported' notification
### Description

When using a browser that doesn't support window.crypto then the no content is loaded (as expected). However the alert() dialog displaying the error message is never displayed, leaving the user with just a blank page. This is caused by a syntax error in browser-compatibility.js, on line 12 there is a trailing , within the alert statement. Most modern browser are able to execute the code as desired despite the mistake, however older browsers such as IE does not do so, and coincidentally it is only these browsers which need to show this message.

Also, did you mean to write ' quotes around undefined? This part, 'undefined' == typeof window will always be false at this point, since the false branch of the condition '!window' at line 3 has been taken. This file is written in a very convoluted way making it hard to read and spot issues like this.

Having a linting process will avoid errors like these. I would also suggest having a more descriptive error message here to aid the user, and avoiding the use of window.alert(); for accessibility and UX reasons.

### PR DESCRIPTION
**Pull request by superdev0714**
Fixes #957 

### Changes description

  - Fixed bug on browser compatible feature
  - Added user friendly UI for unsupported browser, cookie notification

### TODO
Needs to update official app for this update
- https://ctemplar.com/help/answer/browser-support/
- https://ctemplar.com/help/answer/ctemplar-cookie/

Please confirm below images, let me know if update is needed

image

image

### CODE REVIEW

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
I'm not sure if we'll have to translate the message at some point. What do you think?

I would also suggest small text changes:
> We've detected you are running an outdated version of Internet Explorer. _Open with Edge_ or use a different browser.
> Please, take a look at the _list of supported browsers_ for more information.
> Cookies are required to use CTemplar. Please enable them in your browser. Learn more.

I've requested the helpdesk articles already.

**Comment by superdev0714** [comment]
Regarding translation, the above text is out of Angular, so I don't think it's possible easily.

Currently we are processing Old Browser and Cookie independently, do you want to show the text in one place?

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
Ok, I understand.

Then I would only apply my text suggestions and wait for the articles.

**Comment by The-Hidden-Hand** [comment]
@superdev0714 
I've made the changes for you.

**Pull request merged**
