### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by fabianski7**
Some specific terms I did not translate from English into Portuguese. 
In general, they are words like the name of the plans (_Prime_, _Champion_), some specific function like the _Dead man timer_ (the translation can generate a confusing interpretation about its function), and more technical things like _salt cryptographic_, _hash_.

When the translation is available in the client, I will check if any corrections are necessary, due to the context, or even translate the previous terms, if necessary.

### CODE REVIEW

**Comment by atifsaddique211f** [comment]
@fabianski7 this has been merged but it won't be active until we add it into the list of availble languages, we will add it in coming release.

**Comment by atifsaddique211f** [comment]
https://github.com/CTemplar/webclient/releases/tag/v2.1.4

**Comment by fabianski7** [comment]
when i try to change the language to portuguese, i get this

`Failed to save changes, [object Object]`

**Comment by atifsaddique211f** [comment]
I will fix.

**Comment by atifsaddique211f** [comment]
Its fixed.

**Pull request merged**
