### PR TITLE
Fixed issue of opening mail for light mode on dark mode in electron app.

### LINKED ISSUE #1277: Open mail in new window in light mode fails on appimage 2.5.31
### Your environment

AppImage 2.5.31 on Linux

### Steps to reproduce

Change your mode to dark.
Click on the introduction email for a new account.
Notice how its white text on a white background.
Press the little 'sun' icon that has as description that it opens the email in a new tab in light mode.

### Expected behavior

A way to display the mail in light mode.

### Actual behavior

An error from KDE (KIO Client) saying:

> Unable to run the command specified. The file or folder /tmp/.mount_CTemplHfWAJk/resources/app.asar/dist/mail/inbox/page/1/message/7831915 does not exist.

### PR DESCRIPTION
**Pull request by rock-ejin**
Fixes #1277 

### Changes description

- Updated opening URL for view email in a light mode in Electron app.
- Light mode email is opened in the browser.

### CODE REVIEW

**Review by The-Hidden-Hand — CHANGES_REQUESTED** [review]
> Light mode email is opened in the browser.

This isn't gonna work because the browser may have a different or not session at all.

Furthermore, the user experience won't be good because the context switch is not right for users wanting to avoid loading CTemplar from the web browser. Eg. They have browser addons like Grammarly or whatever and want to keep email away from those.

I would like to know the limitations and why did you take this unnatural approach.

Thoughts?

**Comment by rock-ejin** [comment]
Changed to update dark mode to light mode.

**Review by The-Hidden-Hand — CHANGES_REQUESTED** [review]
@rock-ejin 
This is not what we have discussed by chat.

**Comment by rock-ejin** [comment]
I added a button for light/dark mode in header when dark mode is enabled on settings.
Users can change light/dark mode and it is not related to dark mode on settings.
This is working on only the electron app.

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
I've been trying to understand why they have to behave differently on Electron and web while I was looking for a single solution. Could you explain what I am missing?

**Comment by rock-ejin** [comment]
The electron app doesn't provide the new tab with all session data.
I implemented it because there are some differences between Electron and Web.

**Comment by The-Hidden-Hand** [comment]
@rock-ejin 
It has to work the same in the webclient, I don't see the point to have it different.
Could you make the webclient also like this and remove the double case or there is any blocking?

**Comment by rock-ejin** [comment]
I updated webclient for light/dark mode function in header like electron app.

**Pull request merged**
