### PR TITLE
add format validation of invite code

### LINKED ISSUE #1074: Missing error string on wrong invitation code
### Actual behavior

A customer reported the following:

Error1
error2

### PR DESCRIPTION
**Pull request by happyman125**
Fixes #1074 

### Changes description

  - add validation format of invite code.

### CODE REVIEW

**Comment by The-Hidden-Hand** [comment]
@CTemplar/front-end 
I would simply check against regex pattern of XXXX-XXXXXX:

`var res = str.match(/[0-9]{3}-[0-9]{5,6}/);`

You can test and see explanations here: https://regex101.com

Last value 5,6 is because the last set varies from 5 to 6, I believe because backed trims the leading 0 value after code generation.

Thoughts?

**Review by The-Hidden-Hand — CHANGES_REQUESTED** [review]
Check the suggested solution.

**Comment by happyman125** [comment]
I think it is not fit to check valid invite codes.
Because "1234-1234abcd" should be failed as invalid format due to it includes string.
But if we use above regex, we can't detect this. Above regex matches "1234-1234" but can't check all characters.

**Comment by The-Hidden-Hand** [comment]
> I think it is not fit to check valid invite codes.
> Because "1234-1234abcd" should be failed as invalid format due to it includes string.
> But if we use above regex, we can't detect this. Above regex matches "1234-1234" but can't check all characters.

That is the purpose. If the regex doesn't match (returns null) it means the invite code is wrong.

**Comment by happyman125** [comment]
Right. I mean if regex matches (return not null), there is case that invite code is wrong. 
For example, 1234-1234abcd

**Comment by The-Hidden-Hand** [comment]
@happyman125 
I don't understand. The example you set wouldn't match.

If you want to make it extra-safe:

`form_value.match(/^[0-9]{3}-[0-9]{5,6}$/);`

**Comment by happyman125** [comment]
@The-Hidden-Hand I am not sure where you checked above regex but it doesn't match as we want.
image

**Comment by The-Hidden-Hand** [comment]
@happyman125 
It is an example. You can adjust it. Change 3 repetitions by 4 in the first number block.

**Comment by Lissy93** [comment]
@happyman125  You can also refactor this

```
if (this.inviteCode?.includes('-')) {
    const dividedCode = this.inviteCode.split('-');
    for (let i = 0; i < dividedCode.length; i++) {
      if (!/^\d+$/.test(dividedCode[i])) {
        validInviteCode = false;
       }
    }
} else {
    validInviteCode = false;
}
 ```
 
 Into something like this
 
 ```typescript
dividedCode.forEach((dividedCode: String)=> {
    validInviteCode = !!dividedCode.match(/[0-9]{3}-[0-9]{5,6}/);
});
```

**Comment by The-Hidden-Hand** [comment]
Why not just:

`isValid = !!code_str.match(/^[0-9]{4}-[0-9]{5,6}$/);`

**Pull request merged**
