### PR TITLE
v1.1.30

### PR DESCRIPTION
**Pull request by atifsaddique211f**
- Add pagination on contacts page
- Apply optimization to contacts api
- Use CTemplar captcha for free users
- Fix Media kit
- Remove polling and use web sockets.

### CODE REVIEW

**Comment by Git-R-Goin** [comment]
Hi @atifsaddique211f

**Comment by Git-R-Goin** [comment]
I am really interested in this project. Hope to discuss the detail with you.

**Comment by atifsaddique211f** [comment]
> I am really interested in this project. Hope to discuss the detail with you.

@Git-R-Goin What would you like to discuss about the project?

**Comment by Git-R-Goin** [comment]
I'd like to be a contributor for this project @atifsaddique211f

**Comment by atifsaddique211f** [comment]
I have sent you an email . @Git-R-Goin

**Pull request merged**
